<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ETBT7MC" failures="0" tests="1" name="TestNg_Assignments.Assign_161_timeout" time="1.048" errors="1" timestamp="2025-05-19T20:28:21 IST" skipped="0">
  <testcase classname="TestNg_Assignments.Assign_161_timeout" name="forcefailure" time="1.048">
    <error message="Method TestNg_Assignments.Assign_161_timeout.forcefailure() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNg_Assignments.Assign_161_timeout.forcefailure() didn't finish within the time-out 1000
at java.base/java.lang.ProcessImpl.create(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:506)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
at org.openqa.selenium.os.ExternalProcess$Builder.start(ExternalProcess.java:193)
at org.openqa.selenium.manager.SeleniumManager.runCommand(SeleniumManager.java:142)
at org.openqa.selenium.manager.SeleniumManager.getBinaryPaths(SeleniumManager.java:254)
at org.openqa.selenium.remote.service.DriverFinder.getBinaryPaths(DriverFinder.java:102)
at org.openqa.selenium.remote.service.DriverFinder.getDriverPath(DriverFinder.java:55)
at org.openqa.selenium.edge.EdgeDriver.generateExecutor(EdgeDriver.java:71)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:60)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:56)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:48)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:44)
at TestNg_Assignments.Assign_161_timeout.forcefailure(Assign_161_timeout.java:9)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- forcefailure -->
</testsuite> <!-- TestNg_Assignments.Assign_161_timeout -->
